version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: demo_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 123qweASD_
      MYSQL_ROOT_PASSWORD: 123qweASD_
    ports:
      - "3306:3306"

  app:
    depends_on:
      - db
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/demo_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123qweASD_